services:
  ecom_web_app:
    depends_on:
      - shared-postgres
    build:
      context: .
    image: registry.digitalocean.com/nix-ecom-rep/ecomwebapp:latest
    volumes:
      - static_data:/vol/web
    environment:
      - DB_HOST=shared-postgres
      - DB_PORT=5432
    env_file:
      - ./.env
    networks:
      - shared-db
      - dj_ecom_nw-prod
    # command: sh -c "chmod +x /scripts/migrate.sh && sh /scripts/migrate.sh && sh /scripts/entrypoint.sh"
    command: sh -c "/scripts/entrypoint.sh"
    restart: unless-stopped

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    # ports:
    #   - "8080:8080"
      # - "443:443"
    labels:
      - "traefik.enable=true"

      # Main domain
      - "traefik.http.routers.django_ecom_app.rule=Host(`aura.pitech.co.ug`)"
      - "traefik.http.routers.django_ecom_app.tls.domains[0].main=aura.pitech.co.ug"

      # SaaS subdomains
      #- "traefik.http.routers.django_ecom_app.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.aura.pitech.co.ug`)"
      #- "traefik.http.routers.django_ecom_app.tls.domains[0].main=aura.pitech.co.ug"
        # - "traefik.http.routers.django_ecom_app.tls.domains[0].sans=*.aura.pitech.co.ug"

      # CSRF Headers For Django Application that cause Forbidden 403 CSRF verification failed. Request aborted. Errors
      - "traefik.http.middlewares.django-headers.headers.referrerPolicy=same-origin"
      - "traefik.http.middlewares.django-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.django_ecom_app.middlewares=django-headers"

      - "traefik.http.routers.django_ecom_app.entrypoints=websecure"
      - "traefik.http.routers.django_ecom_app.tls.certresolver=letsencrypt-http"
      - "traefik.http.services.django_ecom_app.loadbalancer.server.port=8080"
    networks:
      - dj_ecom_nw-prod
      - web_proxy
    depends_on:
      - ecom_web_app
    restart: unless-stopped

  # postgres_db:
  #   image: postgres:17
  #   env_file:
  #     - ./.env
  #   expose:
  #     - 5432
  #   networks:
  #     - dj_ecom_nw-prod
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   restart: unless-stopped

networks:
  web_proxy:
    external: true
  shared-db:
    external: true
  dj_ecom_nw-prod:
    driver: bridge 

volumes:
  static_data:
  postgres_data:

