# Generated by Django 5.2.4 on 2025-08-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_shippingaddress_shipping_address2_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Shipping_address',
            new_name='shipping_address',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
